// <auto-generated />
using System;
using BeybladeX.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BeybladeX.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260801205808_AddTipoPecaIndex")]
    partial class AddTipoPecaIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BeybladeX.Domain.Entities.Peca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Classificacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("classificacao");

                    b.Property<string>("CodigoHasbro")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_hasbro");

                    b.Property<string>("CodigoTakaraTomy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_takara_tomy");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataLancamento")
                        .HasColumnType("date")
                        .HasColumnName("data_lancamento");

                    b.Property<string>("DirecaoGiro")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("direcao_giro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Peso")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("peso");

                    b.Property<string>("Sistema")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("sistema");

                    b.Property<string>("TipoEstilo")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("tipo_estilo");

                    b.Property<string>("tipo_peca")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoTakaraTomy")
                        .HasDatabaseName("ix_pecas_codigo_takara_tomy");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_pecas_nome");

                    b.HasIndex("Sistema")
                        .HasDatabaseName("ix_pecas_sistema");

                    b.HasIndex("tipo_peca")
                        .HasDatabaseName("ix_pecas_tipo_peca");

                    b.ToTable("pecas", (string)null);

                    b.HasDiscriminator<string>("tipo_peca").HasValue("Peca");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BeybladeX.Domain.Entities.AssistBlade", b =>
                {
                    b.HasBaseType("BeybladeX.Domain.Entities.Peca");

                    b.Property<int>("Ataque")
                        .HasColumnType("integer");

                    b.Property<int>("Defesa")
                        .HasColumnType("integer");

                    b.Property<int>("Stamina")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.ToTable("pecas", t =>
                        {
                            t.Property("Ataque")
                                .HasColumnName("AssistBlade_Ataque");

                            t.Property("Defesa")
                                .HasColumnName("AssistBlade_Defesa");

                            t.Property("Stamina")
                                .HasColumnName("AssistBlade_Stamina");

                            t.Property("Tipo")
                                .HasColumnName("AssistBlade_Tipo");
                        });

                    b.HasDiscriminator().HasValue("AssistBlade");
                });

            modelBuilder.Entity("BeybladeX.Domain.Entities.Bit", b =>
                {
                    b.HasBaseType("BeybladeX.Domain.Entities.Peca");

                    b.Property<int>("Ataque")
                        .HasColumnType("integer");

                    b.Property<int>("Dash")
                        .HasColumnType("integer");

                    b.Property<int>("Defesa")
                        .HasColumnType("integer");

                    b.Property<int>("ResistenciaABurst")
                        .HasColumnType("integer");

                    b.Property<int>("Stamina")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.ToTable("pecas", t =>
                        {
                            t.Property("Ataque")
                                .HasColumnName("Bit_Ataque");

                            t.Property("Defesa")
                                .HasColumnName("Bit_Defesa");

                            t.Property("Stamina")
                                .HasColumnName("Bit_Stamina");

                            t.Property("Tipo")
                                .HasColumnName("Bit_Tipo");
                        });

                    b.HasDiscriminator().HasValue("Bit");
                });

            modelBuilder.Entity("BeybladeX.Domain.Entities.Blade", b =>
                {
                    b.HasBaseType("BeybladeX.Domain.Entities.Peca");

                    b.Property<int>("Ataque")
                        .HasColumnType("integer");

                    b.Property<int>("Defesa")
                        .HasColumnType("integer");

                    b.Property<int>("Stamina")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.ToTable("pecas", t =>
                        {
                            t.Property("Ataque")
                                .HasColumnName("Blade_Ataque");

                            t.Property("Defesa")
                                .HasColumnName("Blade_Defesa");

                            t.Property("Stamina")
                                .HasColumnName("Blade_Stamina");

                            t.Property("Tipo")
                                .HasColumnName("Blade_Tipo");
                        });

                    b.HasDiscriminator().HasValue("Blade");
                });

            modelBuilder.Entity("BeybladeX.Domain.Entities.BladeRatchetIntegrada", b =>
                {
                    b.HasBaseType("BeybladeX.Domain.Entities.Peca");

                    b.Property<int>("Ataque")
                        .HasColumnType("integer");

                    b.Property<int>("Defesa")
                        .HasColumnType("integer");

                    b.Property<int>("Stamina")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.ToTable("pecas", t =>
                        {
                            t.Property("Ataque")
                                .HasColumnName("BladeRatchetIntegrada_Ataque");

                            t.Property("Defesa")
                                .HasColumnName("BladeRatchetIntegrada_Defesa");

                            t.Property("Stamina")
                                .HasColumnName("BladeRatchetIntegrada_Stamina");

                            t.Property("Tipo")
                                .HasColumnName("BladeRatchetIntegrada_Tipo");
                        });

                    b.HasDiscriminator().HasValue("BladeRatchetIntegrada");
                });

            modelBuilder.Entity("BeybladeX.Domain.Entities.LockChip", b =>
                {
                    b.HasBaseType("BeybladeX.Domain.Entities.Peca");

                    b.HasDiscriminator().HasValue("LockChip");
                });

            modelBuilder.Entity("BeybladeX.Domain.Entities.MetalBlade", b =>
                {
                    b.HasBaseType("BeybladeX.Domain.Entities.Peca");

                    b.Property<int>("Ataque")
                        .HasColumnType("integer");

                    b.Property<int>("Defesa")
                        .HasColumnType("integer");

                    b.Property<int>("Stamina")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.ToTable("pecas", t =>
                        {
                            t.Property("Ataque")
                                .HasColumnName("MetalBlade_Ataque");

                            t.Property("Defesa")
                                .HasColumnName("MetalBlade_Defesa");

                            t.Property("Stamina")
                                .HasColumnName("MetalBlade_Stamina");

                            t.Property("Tipo")
                                .HasColumnName("MetalBlade_Tipo");
                        });

                    b.HasDiscriminator().HasValue("MetalBlade");
                });

            modelBuilder.Entity("BeybladeX.Domain.Entities.OverBlade", b =>
                {
                    b.HasBaseType("BeybladeX.Domain.Entities.Peca");

                    b.Property<int>("Ataque")
                        .HasColumnType("integer");

                    b.Property<int>("Defesa")
                        .HasColumnType("integer");

                    b.Property<int>("Stamina")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("OverBlade");
                });

            modelBuilder.Entity("BeybladeX.Domain.Entities.Ratchet", b =>
                {
                    b.HasBaseType("BeybladeX.Domain.Entities.Peca");

                    b.Property<int>("Ataque")
                        .HasColumnType("integer");

                    b.Property<int>("Defesa")
                        .HasColumnType("integer");

                    b.Property<int>("Stamina")
                        .HasColumnType("integer");

                    b.ToTable("pecas", t =>
                        {
                            t.Property("Ataque")
                                .HasColumnName("Ratchet_Ataque");

                            t.Property("Defesa")
                                .HasColumnName("Ratchet_Defesa");

                            t.Property("Stamina")
                                .HasColumnName("Ratchet_Stamina");
                        });

                    b.HasDiscriminator().HasValue("Ratchet");
                });
#pragma warning restore 612, 618
        }
    }
}
