@BeybladeX.Api_HostAddress = http://localhost:5049

GET {{BeybladeX.Api_HostAddress}}/api/v1/pecas/Dran Sword
Accept: application/json

###

GET {{BeybladeX.Api_HostAddress}}/health
Accept: application/json

###
